-------------------------------------------------------------------------------
-- Title      : Components package (generated by Emacs VHDL Mode 3.33.27)
-- Project    : reconf_demo_mult
-------------------------------------------------------------------------------
-- File       : reconf_demo_mult_components.vhd
-- Author     : Pavel Sorejs <sorejs@gmail.com>
-- Company    : 
-- Created    : 2010-01-18
-- Last update: 2010-01-18
-- Platform   : 
-- Standard   : VHDL'87
-------------------------------------------------------------------------------
-- Description: 
-------------------------------------------------------------------------------
-- Copyright (c) 2010 
-------------------------------------------------------------------------------
-- Revisions  :
-- Date        Version  Author  Description
-- 2010-01-18  1.0      pavel	Created
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use IEEE.std_logic_arith.all;

-------------------------------------------------------------------------------

package reconf_demo_mult_components is

    ---------------------------------------------------------------------------
    -- Component declarations
    ---------------------------------------------------------------------------

    component UART_VHDL
        generic (
            sysfreq  : integer;
            baudrate : integer);
        port (
            clk         : in  std_logic;
            rst         : in  std_logic;
            writeData   : in  std_logic_vector(7 downto 0);
            write       : in  std_logic;
            unitBussy   : out std_logic;
            readData    : out std_logic_vector(7 downto 0);
            read        : in  std_logic;
            dataPresent : out std_logic;
            serialIn    : in  std_logic;
            serialOut   : out std_logic);
    end component;

    component datapath
        port (
            inputA : in  std_logic_vector(7 downto 0);
            inputB : in  std_logic_vector(7 downto 0);
            output : out std_logic_vector(15 downto 0));
    end component;
 
    component test_ctl
        generic (
            REG_COUNT : integer);
        port (
            clk           : in  std_logic;
            rst           : in  std_logic;
            registers_in  : in  std_logic_vector((REG_COUNT-1)*8 + 7 downto 0);
            registers_out : out std_logic_vector((REG_COUNT-1)*8 + 7 downto 0);
            writeData     : out std_logic_vector(7 downto 0);
            write         : out std_logic;
            unitBussy     : in  std_logic;
            readData      : in  std_logic_vector(7 downto 0);
            read          : out std_logic;
            dataPresent   : in  std_logic);
    end component;

end reconf_demo_mult_components;

-------------------------------------------------------------------------------
