SRCS_SYNTH=reconf_demo_mult_components.vhd datapath.vhd    test_ctl.vhd  top.vhd  uart.vhd
SRCS_SIM=
PART=xc3s1000-FT256-4
TOP_NAME=top

#============= END OF CONFIG ======================
include ~/ise/make-system/xilinx_rules.mk